name: "Run Microsoft Rewards Script (randomized start around 08:00 Toronto, EST-only)"

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
    inputs:
      simulate_schedule:
        description: 'Set to true to simulate schedule behaviour (enable jitter) for manual runs)'
        required: false
        default: 'false'

jobs:
  run-rewards:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      NODE_VERSION: '20'
      SIMULATE_SCHEDULE: ${{ github.event.inputs.simulate_schedule || 'false' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: "Decide whether this scheduled run should continue (EST-only target: local 08:00)"
        shell: bash
        run: |
          set -euo pipefail
          EVENT_NAME="${GITHUB_EVENT_NAME:-}"
          if [ "$EVENT_NAME" = "workflow_dispatch" ] && [ "${SIMULATE_SCHEDULE:-}" != "true" ]; then
            echo "Manual run requested (no hour check)."
          else
            LOCAL_HOUR=$(TZ='America/Toronto' date +%H | sed 's/^0//')
            if [ "$LOCAL_HOUR" -ne 8 ]; then
              echo "Local hour is not 8 (EST target) — exiting."
              exit 0
            fi
            echo "Local hour is 8 — continuing."
          fi

      - name: "Compute random jitter (0..90 minutes)"
        shell: bash
        run: |
          set -euo pipefail
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ "${SIMULATE_SCHEDULE:-}" != "true" ]; then
            echo "Manual run — skipping jitter."
          else
            JITTER_SEC=$(( $(od -An -N4 -tu4 /dev/urandom | tr -d ' ') % (90*60 + 1) ))
            echo "Sleeping $JITTER_SEC seconds (jitter up to 90m)."
            sleep "$JITTER_SEC"
          fi

      - name: "Write src/accounts.json from secret (robust + debug)"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p src
          # (the same robust writer you already have — omitted here for brevity)
          # ... paste your robust writer script here or keep the existing step ...
          echo "WROTE accounts.json (debug omitted in snippet)"

      - name: "Install Node dependencies (npm ci)"
        run: npm ci --no-audit --no-fund

      - name: "Cache Playwright browser binaries"
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browser-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browser-cache-${{ runner.os }}-

      - name: "Install Playwright Chromium + OS dependencies"
        shell: bash
        run: |
          set -euo pipefail
          npx --yes playwright install --with-deps chromium

      - name: "Install xvfb (virtual X server) so headed browsers can run"
        shell: bash
        run: |
          set -eux
          sudo apt-get update
          # install Xvfb and some typical X libs (keeps package small)
          sudo apt-get install -y xvfb
          # optionally ensure fonts, etc. Playwright --with-deps often installed wide deps already
          dpkg -l | head -n 20

      - name: "Build the project"
        run: npm run build

      - name: "Create runtime File polyfill (fallback)"
        shell: bash
        run: |
          mkdir -p dist
          cat > dist/polyfill-file.js <<'EOF'
          if (typeof globalThis.File === 'undefined') {
            globalThis.File = class File extends Blob {
              constructor(parts = [], name = '', options = {}) {
                super(parts, options);
                this.name = String(name);
                this.lastModified = options && options.lastModified ? Number(options.lastModified) : Date.now();
              }
            };
          }
          EOF

      - name: "Run the built script under Xvfb (headed allowed) and save logs"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p logs
          # Run headed browser under virtual X server. This lets headless:false work.
          # Use --auto-servernum so multiple jobs don't collide, and set a reasonable screen size.
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' \
            node -r ./dist/polyfill-file.js ./dist/index.js 2>&1 | tee logs/script.log || true
          echo "Captured logs to logs/script.log"

      - name: "Sanitize logs"
        shell: bash
        run: |
          set -euo pipefail
          cp logs/script.log logs/script.log.raw || true
          sed -E -i 's/("password"[[:space:]]*:[[:space:]]*)"[^"]*"/\1"***REDACTED***"/Ig' logs.script.log
          # other redaction lines...
          rm -f logs/script.log.raw || true

      - name: "Upload logs"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: microsoft-rewards-logs-${{ github.run_id }}
          path: logs/script.log
