name: "Run Microsoft Rewards Script (randomized start around 08:00 Toronto local)"

on:
  schedule:
    # 09:00 Toronto local --> 13:00 UTC (DST) and 14:00 UTC (standard)
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:
    inputs:
      simulate_schedule:
        description: 'Set to true to simulate schedule behaviour (enable jitter) for manual runs)'
        required: false
        default: 'false'

jobs:
  run-rewards:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      NODE_VERSION: '20'
      SIMULATE_SCHEDULE: ${{ github.event.inputs.simulate_schedule || 'false' }}
      JOB_INDEX: '0'
      GROUP_SIZES: '3,2,2'
      TARGET_HOUR_TORONTO: '9'
      MAX_JITTER_SECONDS: '4320'   # 1.2 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: "Decide whether this scheduled run should continue (Toronto target gate)"
        shell: bash
        run: |
          set -euo pipefail
          EVENT_NAME="${GITHUB_EVENT_NAME:-}"
          if [ "$EVENT_NAME" = "workflow_dispatch" ] && [ "${SIMULATE_SCHEDULE:-}" != "true" ]; then
            echo "Manual run requested (no hour check)."
          else
            LOCAL_HOUR=$(TZ='America/Toronto' date +%H | sed 's/^0//')
            echo "Toronto local hour: ${LOCAL_HOUR}"
            if [ "$LOCAL_HOUR" -ne "${TARGET_HOUR_TORONTO}" ]; then
              echo "Local hour is not ${TARGET_HOUR_TORONTO} — exiting."
              exit 0
            fi
            echo "Local hour matches target (${TARGET_HOUR_TORONTO}) — continuing."
          fi

      - name: "Compute random jitter (0..MAX_JITTER_SECONDS)"
        shell: bash
        run: |
          set -euo pipefail
          if [ "${GITHUB_EVENT_NAME:-}" = "workflow_dispatch" ] && [ "${SIMULATE_SCHEDULE:-}" != "true" ]; then
            echo "Manual run — skipping jitter."
            JITTER_SEC=0
          else
            MAX=${MAX_JITTER_SECONDS:-4320}
            JITTER_SEC=$(( $(od -An -N4 -tu4 /dev/urandom | tr -d ' ') % (MAX + 1) ))
            echo "Sleeping $JITTER_SEC seconds (jitter up to $MAX)."
            sleep "$JITTER_SEC"
          fi

      - name: "Write src/accounts.json from secret (robust + debug)"
        shell: bash
        env:
          ACCOUNTS_JSON_B64: ${{ secrets.ACCOUNTS_JSON_B64 || '' }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON || '' }}
        run: |
          set -euo pipefail
          mkdir -p src
          echo "=== Debug: repo root listing ==="
          ls -la

          if [ -n "${ACCOUNTS_JSON_B64:-}" ]; then
            echo "Found ACCOUNTS_JSON_B64 (non-empty) — decoding to src/accounts.json"
            if printf '%s' "$ACCOUNTS_JSON_B64" | base64 --decode > src/accounts.json 2>/dev/null; then
              echo "Decoded ACCOUNTS_JSON_B64 -> src/accounts.json"
            else
              echo "ERROR: failed to decode ACCOUNTS_JSON_B64" >&2
              exit 1
            fi

          elif [ -n "${ACCOUNTS_JSON:-}" ]; then
            echo "Found ACCOUNTS_JSON (non-empty) — processing..."
            RAW="$ACCOUNTS_JSON"
            case "$RAW" in
              \"*\" ) RAW="${RAW#\"}"; RAW="${RAW%\"}" ;;
              \'*\' ) RAW="${RAW#\'}"; RAW="${RAW%\'}" ;;
            esac
            case "$RAW" in
              [\{[]* )
                printf '%s' "$RAW" > src/accounts.json
                echo "Wrote raw JSON to src/accounts.json"
                ;;
              * )
                TMP=$(mktemp)
                if printf '%s' "$RAW" | base64 --decode > "$TMP" 2>/dev/null; then
                  if command -v jq >/dev/null 2>&1; then
                    if jq . "$TMP" >/dev/null 2>&1; then
                      mv "$TMP" src/accounts.json
                      echo "Decoded base64 secret and moved to src/accounts.json (validated with jq)"
                    else
                      rm -f "$TMP"
                      echo "ERROR: ACCOUNTS_JSON appears base64 but decoded content not valid JSON." >&2
                      exit 1
                    fi
                  else
                    if node -e "try{JSON.parse(require('fs').readFileSync('$TMP','utf8')); process.exit(0)}catch(e){ process.exit(2) }"; then
                      mv "$TMP" src/accounts.json
                      echo "Decoded base64 secret and moved to src/accounts.json (validated with node)"
                    else
                      rm -f "$TMP"
                      echo "ERROR: ACCOUNTS_JSON appears base64 but decoded content not valid JSON (node check failed)." >&2
                      exit 1
                    fi
                  fi
                else
                  echo "ERROR: ACCOUNTS_JSON not raw JSON and not valid base64 -> cannot interpret." >&2
                  rm -f "$TMP" 2>/dev/null || true
                  exit 1
                fi
                ;;
            esac

          else
            echo "No ACCOUNTS_JSON_B64 or ACCOUNTS_JSON secret found in runner environment." >&2
            echo "Attempting to fallback to example files in repo..."
            if [ -f src/accounts.example.json ]; then
              cp src/accounts.example.json src/accounts.json
              echo "Copied src/accounts.example.json -> src/accounts.json (example fallback)."
            elif [ -f accounts.example.json ]; then
              cp accounts.example.json src/accounts.json
              echo "Copied accounts.example.json -> src/accounts.json (example fallback)."
            else
              echo "ERROR: No secrets and no example file available. Please set ACCOUNTS_JSON or ACCOUNTS_JSON_B64 secret." >&2
              ls -la || true
              exit 1
            fi
          fi

          if command -v jq >/dev/null 2>&1; then
            jq . src/accounts.json >/dev/null || { echo "Invalid JSON in src/accounts.json" >&2; exit 1; }
            echo "src/accounts.json validated by jq."
          else
            node -e "try{JSON.parse(require('fs').readFileSync('src/accounts.json','utf8')); console.log('src/accounts.json validated by node')}catch(e){ console.error('Invalid JSON:', e.message); process.exit(2) }"
          fi

      - name: "Trim accounts.json to this job's partition (seeded shuffle by Toronto date)"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          node - <<'NODE'
const fs = require('fs');
const all = JSON.parse(fs.readFileSync('src/accounts.json','utf8'));
const jobIndex = Number(process.env.JOB_INDEX||'0');
const groupSizes = (process.env.GROUP_SIZES||'3,2,2').split(',').map(Number);
const seedDate = new Date().toLocaleDateString('en-CA',{ timeZone: 'America/Toronto' }); // YYYY-MM-DD
function seedFromString(s){ let h=2166136261>>>0; for(let i=0;i<s.length;i++){ h=Math.imul(h ^ s.charCodeAt(i),16777619)>>>0;} return h>>>0; }
function mulberry32(a){ return function(){ let t = a += 0x6D2B79F5; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; } }
const rng = mulberry32(seedFromString(seedDate));
const arr = all.slice();
for(let i=arr.length-1;i>0;i--){ const j=Math.floor(rng()*(i+1)); [arr[i],arr[j]]=[arr[j],arr[i]]; }
let start=0; for(let i=0;i<jobIndex;i++) start += (groupSizes[i]||0);
const mySize = groupSizes[jobIndex]||0;
const slice = arr.slice(start, start+mySize);
fs.writeFileSync('dist/accounts.json', JSON.stringify(slice, null, 2));
console.log('SeedDate:', seedDate, 'Assigned', slice.length, 'accounts to job', jobIndex);
NODE

      - name: "Install Node dependencies (npm ci)"
        run: npm ci --no-audit --no-fund

      - name: "Cache Playwright browser binaries"
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browser-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browser-cache-${{ runner.os }}-

      - name: "Install Playwright Chromium + OS dependencies"
        shell: bash
        run: |
          set -euo pipefail
          npx --yes playwright install --with-deps chromium

      - name: "Install xvfb (virtual X server) so headed browsers can run"
        shell: bash
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y xvfb
          dpkg -l | head -n 20

      - name: "Build the project"
        run: npm run build

      - name: "Ensure dist/accounts.json exists (copy after build)"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          if [ -f dist/accounts.json ]; then
            echo "dist/accounts.json present"
          elif [ -f src/accounts.json ]; then
            cp src/accounts.json dist/accounts.json
            echo "Copied src/accounts.json -> dist/accounts.json"
          else
            echo "WARNING: src/accounts.json missing — job may fail." >&2
            ls -la src || true
          fi

      - name: "Create runtime File polyfill (fallback)"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          cat > dist/polyfill-file.js <<'EOF'
if (typeof globalThis.File === 'undefined') {
  globalThis.File = class File extends Blob {
    constructor(parts = [], name = '', options = {}) {
      super(parts, options);
      this.name = String(name);
      this.lastModified = options && options.lastModified ? Number(options.lastModified) : Date.now();
    }
  };
}
EOF
          echo "Wrote dist/polyfill-file.js"

      - name: "Run the built script under Xvfb (headed allowed) and save logs"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p logs
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' \
            sh -c "stdbuf -oL -eL node -r ./dist/polyfill-file.js ./dist/index.js 2>&1 | tee -a logs/script.log" || true
          echo "Captured logs to logs/script.log"
          ps auxww > logs/ps-auxww.txt || true
          ls -laR > logs/ls-laR.txt || true
          env > logs/env.raw || true

      - name: "Sanitize logs"
        shell: bash
        run: |
          set -euo pipefail
          cp logs/script.log logs/script.log.raw || true
          sed -E -i 's/("password"[[:space:]]*:[[:space:]]*)"[^"]*"/\1"***REDACTED***"/Ig' logs/script.log || true
          sed -E -i 's/([Pp]ass(word)?[[:space:]]*[:=][[:space:]]*)[^[:space:],;]+/\1***REDACTED***/g' logs/script.log || true
          sed -E -i 's/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/***REDACTED_EMAIL***/g' logs/script.log || true
          sed -E -i 's/([Aa]uthorization[[:space:]]*[:=][[:space:]]*(Bearer|Basic)?[[:space:]]*)[^[:space:]]+/\1***REDACTED***/g' logs/script.log || true
          sed -E -i 's/[A-Za-z0-9+/]{40,}={0,2}/***REDACTED_BASE64***/g' logs/script.log || true
          cp logs/env.raw logs/env.raw.bak || true
          sed -E -i 's/([A-Za-z0-9_]+)=([^[:space:]]+)/\1=***REDACTED_ENV***/g' logs/env.raw || true

      - name: "Upload logs"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: microsoft-rewards-logs-${{ github.run_id }}-group0
          path: |
            logs/script.log
            logs-full.tar.gz
            logs/*
